import { useState } from "react";
import { X, ChevronRight, Trash2, Sparkles } from "lucide-react";

interface Report {
  id: string;
  title: string;
  subtitle: string;
  date: string;
}

interface ReportsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onViewReport: (reportId: string) => void;
}

export function ReportsModal({ isOpen, onClose, onViewReport }: ReportsModalProps) {
  const [reports, setReports] = useState<Report[]>([
    {
      id: "1",
      title: "Performance Analysis Report (December 2025)",
      subtitle: "Automatically generated by the system",
      date: "Dec 31, 2025",
    },
    {
      id: "2",
      title: "Performance Analysis Report (November 2025)",
      subtitle: "Automatically generated by the system",
      date: "Nov 30, 2025",
    },
    {
      id: "3",
      title: "Performance Analysis Report (October 2025)",
      subtitle: "Automatically generated by the system",
      date: "Oct 31, 2025",
    },
    {
      id: "4",
      title: "Performance Analysis Report (September 2025)",
      subtitle: "Automatically generated by the system",
      date: "Sep 30, 2025",
    },
  ]);

  const handleDelete = (reportId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setReports(reports.filter(report => report.id !== reportId));
  };

  const handleViewReport = (reportId: string) => {
    onViewReport(reportId);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 dark:bg-black/70"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative bg-white dark:bg-gray-950 rounded-lg shadow-xl w-full max-w-2xl mx-4 max-h-[80vh] flex flex-col border border-gray-200 dark:border-gray-800">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-800">
          <h2 className="text-gray-900 dark:text-white">Performance Reports</h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-900 rounded-full transition-colors"
          >
            <X className="w-5 h-5 text-gray-500 dark:text-gray-400" />
          </button>
        </div>

        {/* Reports List */}
        <div className="flex-1 overflow-y-auto p-6">
          {reports.length > 0 ? (
            <div className="space-y-3">
              {reports.map((report) => (
                <div
                  key={report.id}
                  className="flex items-center justify-between p-4 border border-gray-200 dark:border-gray-800 rounded-lg bg-white dark:bg-gray-950 hover:bg-gray-50 dark:hover:bg-gray-900 transition-colors cursor-pointer"
                  onClick={() => handleViewReport(report.id)}
                >
                  {/* Left side - Title and Subtitle */}
                  <div className="flex-1 min-w-0 mr-4">
                    <h3 className="text-gray-900 dark:text-white mb-1">
                      {report.title}
                    </h3>
                    <div className="flex items-center gap-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 flex-shrink-0" />
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        {report.subtitle}
                      </p>
                    </div>
                  </div>

                  {/* Right side - Date and Actions */}
                  <div className="flex items-center gap-3 flex-shrink-0">
                    <span className="text-sm text-gray-500 dark:text-gray-400">
                      {report.date}
                    </span>
                    <button
                      onClick={() => handleViewReport(report.id)}
                      className="p-2 hover:bg-gray-200 dark:hover:bg-gray-800 rounded-full transition-colors"
                    >
                      <ChevronRight className="w-5 h-5 text-gray-600 dark:text-gray-300" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
              <p className="text-gray-500 dark:text-gray-400">
                No reports available yet.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}